try {
    // throw new Error("Servidor fora do ar")
    console.log("sistema Iniciado");
} catch (error) {
    console.log("O seguinte erro aconteceu:" ,  error);
}finally{
    console.log("Sistema Encerrado...");
}